version: '3.8'
services: 
    api-service:
        image: api-express:v1
        stdin_open: true
        expose: 
            - 3001
        ports: 
            - 3001:3001
        depends_on: 
            - mongo
    mongo:
        image: mongo
        ports: 
            - 27017:27017